const teclas_nvimRZ = [
  {
    categoria: "teclas",
    contexto: "",
    titulo: "",
    codigo: "",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "",
    titulo: "tecla SETA PARA CIMA no Nvim com api vim",
    codigo: "up",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "",
    titulo: "tecla SETA PARA BAIXO no Nvim com api vim",
    codigo: "down",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "",
    titulo: "tecla SETA DIREITA no Nvim com api vim",
    codigo: "Left",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "",
    titulo: "tecla SETA ESQUERDA no Nvim com api vim",
    codigo: "< Right >",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "",
    titulo: "Espaço",
    codigo: "< Space >",
    conceito: "teclas no vimscript puro começam com minusculo, no Nvim com api vim começam com Maiusculo",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "nvim",
    titulo: "tecla alt",
    codigo: "<A>",
    OBS: 'TEM QUE PULA RO ABRRA DA MEMORIA -> , ":m .+1<CR>==", opts)',
    conceito: "no nvim as variaveis de teclas começam com Maiusculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "nvim",
    titulo: "teclas funcionais",
    codigo: "F10 ou numero da F<numero>",
    conceito: "no nvim as variaveis de teclas começam com Maiusculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "nvim",
    titulo: "control",
    codigo: "C",
    conceito: "no nvim as variaveis de teclas começam com Maiusculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "nvim",
    titulo: "shift",
    codigo: "S",
    conceito: "no nvim as variaveis de teclas começam com Maiusculo.",
    obs: "#nulo",
  },
];
