const keymaps_editor_nvim = [
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: '',
		plugin: '#null',
		key: '',
		modo: 'all',
		command: '',
		obs: '#null',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'visualizar arquivos ocultos no NERDTree',
		modo: '',
		plugin: 'NERDTree',
		key: 'S-h  // shift+h',
		modo: 'all',
		command: '',
		obs: '#null',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'identar linha',
		plugin: '#null',
		key: 'Tab',
		modo: 'visual',
		command: '',
		obs: '#null',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'desidentar linha',
		plugin: '#null',
		key: 'S-Tab',
		modo: 'visual',
		command: '',
		obs: '#null',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'fecha buffer',
		key: 'f12',
		modo: 'all',
		command: '',
		obs: 'desc = Close buffer',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'Terminal Vertical Toggle',
		key: '<leader>tt',
		modo: 'all',
		command: 'p',
		obs: 'desc = ToggleTerm vertical ',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'Comentário em linha',
		key: '<leader>x',
		modo: 'normal',
		command: '#null',
		obs: ' ',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'Comentário em bloco',
		key: '<leader>cc',
		modo: 'normal',
		command: '#null',
		obs: ' ',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'find aquivos - telescope',
		key: '<leader>ff',
		modo: 'normal',
		command: '#null',
		obs: ' ',
	},
	{
		editor: 'nvim',
		categoria: 'keymaps',
		titulo: 'find aquivos buffers abertos - telescope',
		key: '<leader>fb',
		modo: 'normal',
		command: '#null',
		obs: ' ',
	},
]
