const teclas_vscode = [
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "",
    codigo: "",
    conceito: "no <???> as variaveis de teclas começam com <???>",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla seta para baixo",
    codigo: "down",
    conceito: "no <???> as variaveis de teclas começam com <???>",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla seta para cima",
    codigo: "up",
    conceito: "no <???> as variaveis de teclas começam com <???>",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla esc",
    codigo: "escape",
    conceito: "no vscode as variaveis de teclas começam com Minúsculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla espaco",
    codigo: "space",
    conceito: "no vscode as variaveis de teclas começam com Minúsculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla tab",
    codigo: "tab",
    conceito: "no vscode as variaveis de teclas começam com Minúsculo.",
    obs: "#nulo",
  },
  {
    categoria: "teclas",
    contexto: "vscode",
    titulo: "tecla alt",
    codigo: "alt",
    conceito: "alt é uma tecla modificadora -- no vscode as variaveis de teclas começam com Minúsculo.",
    obs: "#nulo",
  },
];
